---
title: "PDA_EDA"
author: "Maria Pia El Asmar & Hasini Gunawardena"
date: "10/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages to be put in the next section at the end of the project
```{r setup, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(DT)
library(Hmisc)  
library(tidyquant)
library(ggthemes)
library(RColorBrewer)
library(corrplot)
library(psych)
library(GGally)
library(corrr)
library(corrplot)
library(ggcorrplot)
library(kableExtra)
library(DataExplorer)
library(inspectdf)
```


```{r setup2, echo = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  cache = TRUE,
  fig.retina = 0.8, # figures are either vectors or 300 dpi diagrams
  dpi = 300,
  out.width = "70%",
  fig.align = 'center',
  fig.width = 6,
  fig.asp = 0.618,  
  fig.show = "hold"
)

ggplot2::theme_set(ggplot2::theme_light())

options(
  digits = 3,
  str = strOptions(strict.width = "cut"),
  width = 69,
  tibble.width = 69,
  cli.unicode = FALSE
)
```


# Introduction

```{r, echo=FALSE}
GermanCredit <- read.csv(
  here::here("data/GermanCredit.csv"),
  header = TRUE,
  sep = ";",
  dec = "."
)[,-1]

```


# Exploratory Data Analysis

## Structure & Summary

```{r, echo=FALSE}
str(GermanCredit)
```


```{r, echo=FALSE}
head(GermanCredit)
```

Transformation of integer variables into correct categorical ones:

```{r, echo=FALSE}

for (i in (1:31)) {
  if (is.integer(GermanCredit[,i]) & i != 2 & i != 8  & i !=10  & i != 13  & i !=22  & i !=26  & i != 28) {
  GermanCredit[,i] <- as.factor(GermanCredit[,i])
  }
}

# changing education
for (i in 1:1000){
  if (GermanCredit[i,8] == "-1") {
    GermanCredit[i,8] <- "1"
    GermanCredit[,8] <- as.factor(GermanCredit[,8])
  }
}


```

```{r, echo=FALSE}
str(GermanCredit) #la structure après les modifs. Je t'ai noté les trucs bizarres que j'ai vu mais n'hésites pas à re-checker au cas où
```

```{r, echo=FALSE}
library(psych)
library(Hmisc)
summary(GermanCredit)
describe(GermanCredit)
```

```{r, echo=FALSE}
library(DT)
datatable(head(GermanCredit), class = "cell-border stripe") #Ca apparait pas haha 
# PIA: à checker quand on va knit

```

```{r, echo=FALSE}
library(DataExplorer)
plot_intro(GermanCredit)
```

```{r, echo=FALSE}
library(inspectdf)
types<-inspect_types(GermanCredit)
show_plot(types, col_palette=2)

num.var<-inspect_num(GermanCredit)
show_plot(num.var, col_palette=3)

cat.var<-inspect_cat(GermanCredit) 
show_plot(cat.var) 

```

## Histogram & Density

```{r, echo=FALSE}
library(ggplot2)
plot_histogram(GermanCredit[,-31])
plot_density(GermanCredit[,-31],
             ggtheme = theme_bw())
```

## Side-by-side boxplots

```{r, echo=FALSE}
plot_boxplot(GermanCredit,
             by = 'RESPONSE',
             ncol = 2,
             title = "Side-by-side boxplots")

## PIA
# age has an outlier. one person is 125 years old!
GermanCredit %>% 
  select (AGE, RESPONSE) %>% 
  arrange(desc(AGE))
#--> enlever observation 125 ans

```

```{r, echo=FALSE}
lblue <- "#6699CC"
par(mfrow = c(2, 3))

boxplot(AGE ~ RESPONSE, data = GermanCredit, xlab = "Response", notch = T, 
    varwidth = T, col = lblue)
boxplot(AMOUNT ~ RESPONSE, data = GermanCredit, xlab = "Response", varwidth = T, col = lblue)
boxplot(DURATION ~ RESPONSE, data = GermanCredit, xlab = "Response", varwidth = T, col = lblue)
boxplot(INSTALL_RATE ~ RESPONSE, data = GermanCredit, xlab = "Response", varwidth = T, col = lblue)
boxplot(NUM_CREDITS ~ RESPONSE, data = GermanCredit, xlab = "Response", varwidth = T, col = lblue)


```

## Correlations

```{r, echo=FALSE, fig.width= 8, fig.height= 7}
library(GGally)
plot_correlation(GermanCredit, type= 'c', cor_args = list( 'use' = 'complete.obs'))
#ggpairs(GermanCredit, ggplot2::aes(colour = RESPONSE)) ça prend trop de temps à run
#Il y a plein plein de plots de correlation différentes, du coup j'en ai seulement mis 2 mais dis moi si y en a un qui te plaît plus


```

## Good vs Bad credits
```{r, echo=FALSE}
#from WS 4
library(explore)
GermanCredit %>% explore(RESPONSE)


#CHECK QUE TOUTES LES VARIABLES ON ETE CONSIDERE
GermanCredit %>% 
  select(TELEPHONE, RADIO.TV, RESPONSE) %>% 
  explore_all(target = RESPONSE)

GermanCredit %>% 
  select(NEW_CAR, USED_CAR,FURNITURE,EDUCATION, RESPONSE) %>% 
  explore_all(target = RESPONSE)

GermanCredit %>% 
  select(FOREIGN, MALE_DIV, MALE_SINGLE, MALE_MAR_or_WID, RESPONSE) %>% 
  explore_all(target = RESPONSE)

GermanCredit %>% 
  select(GUARANTOR, CO.APPLICANT, PROP_UNKN_NONE, OTHER_INSTALL, RESPONSE) %>% 
  explore_all(target = RESPONSE)

GermanCredit %>% 
  select(REAL_ESTATE, RENT, OWN_RES, RETRAINING, RESPONSE) %>% 
  explore_all(target = RESPONSE)

```














