---
title: "Modeling"
author: "Maria Pia El Asmar & Hasini Gunawardena"
date: "10/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Partition of Data

```{r, echo=FALSE}

row.order <- sample(c(1:1000)) # first randomize the order of the rows
german.tr <- GermanCredit[row.order[1:750],] # take the first 750 (random) rows of german for the training set
german.te <- GermanCredit[row.order[751:1000],]


```


# Decision Tree with Caret

```{r, echo=FALSE}
library(caret)
ct.caret <- train(RESPONSE ~ .,
                         data=german.tr,
                         method="rpart",
                         preProcess=c("center", "scale"),
                         trControl=trainControl(method="repeatedcv", number=10,
                         repeats=10, verboseIter=FALSE, sampling = "down")
                         )

```

  ## Best Complexity parameter 
```{r, echo=FALSE}
print(ct.caret) 
plot(ct.caret)

```

  ## Confusion Matrix
```{r, echo=FALSE}
confusionMatrix(predict.train(ct.caret, newdata = german.te), 
                german.te$RESPONSE)


``` 

  ## Tree drawing
```{r, echo=FALSE}
plot(ct.caret$finalModel)
text(ct.caret$finalModel)

```

# Neural Network with Caret


```{r, echo=FALSE, include = FALSE}
set.seed(2006)
credit.nn.caret <- train (
  form = RESPONSE ~ .,
  data = german.tr,
  method = "nnet",
  preProcess = c("center", "scale"),
  trControl = trainControl(
    method = "repeatedcv",
    number = 10,
    repeats = 10,
    verboseIter = FALSE,
    sampling = "down")
)



```


  ## Accuracy measure
  
```{r, echo=FALSE}
print(credit.nn.caret)

```

  ## Confusion Matrix
```{r, echo=FALSE}
confusionMatrix(predict.train(credit.nn.caret, newdata = german.te), 
                german.te$RESPONSE)
``` 

  ## Neural Network drawing
```{r, echo=FALSE}
library(NeuralNetTools)
plotnet(credit.nn.caret, pos_col = "darkgreen", neg_col = "darkblue")

```

# Logistic regression with caret

```{r, echo=FALSE}
credit.log.caret <-
  train(
    form = RESPONSE ~ .,
    data = german.tr,
    method = "glm",
    preProcess = c("center", "scale"),
    trControl = trainControl(
      method = "repeatedcv",
      number = 10,
      repeats = 10,
      verboseIter = FALSE,
      sampling = "down"
    )
  )


```


  ## Accuracy measure
  
```{r, echo=FALSE}
print(credit.log.caret)
summary(credit.log.caret)

```

  ## Confusion Matrix
```{r, echo=FALSE}
confusionMatrix(predict.train(credit.log.caret, newdata = german.te),
                german.te$RESPONSE)


``` 


# Discriminant Analysis

```{r, echo=FALSE}


```

# KNN

```{r, echo=FALSE}


```

# Support Vector Machine 

```{r, echo=FALSE}


```

# Ensemble methods (Random Forest)

```{r, echo= FALSE}


```

